version: '3'

services:
  message-listener-service:
    build: ./message-listener-service
    depends_on:
      - rabbitmq
    command:
      node index.js
    volumes:
      - ./message-listener-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9090:9090
    links:
      - rabbitmq
  message-processor-service:
    build: ./message-processor-service
    depends_on:
      - rabbitmq
    command:
      node index.js
    volumes:
      - ./message-processor-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9099:9099
    links:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
